#!/bin/bash

PYTHON=$(which python3)

sudo apt install python3-venv

$PYTHON -m venv ./env

source ./env/bin/activate

export PYTHONPATH=${PWD}

pip install --upgrade pip
pip install -r requirements.txt

chmod +x ./src/*/*.py
